services:
  backend_auth:
    build:
      context: ./backend_auth
      dockerfile: Dockerfile
    develop:
      watch:
        - path: ./backend_auth
          action: rebuild
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - PORT=5000
    restart: unless-stopped

  ai_backend:
    build: 
      context: ./backend_ai
      dockerfile: Dockerfile 
    develop:
      watch:
        - path: ./backend_ai
          action: rebuild    
    container_name: backend_ai
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    

  ollama:
      image: ${OLLAMA_IMAGE:-ollama/ollama:latest}
      container_name: ollama
      ports:
        - "11434:11434"
      volumes:
        - ./ollama_data:/root/.ollama

      devices:
      - /dev/kfd
      - /dev/dri
      
      deploy:
        resources:
          reservations:
            devices:
              - driver: ${GPU_DRIVER:-none}
                count: ${GPU_COUNT:-0}
                capabilities: [gpu]
